// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddClothes: typeof import('./components/Clothes/AddClothes.vue')['default']
    AddNavTag: typeof import('./components/Home/AddNavTag.vue')['default']
    AddNewTag: typeof import('./components/Blog/AddNewTag.vue')['default']
    BlogSide: typeof import('./components/Blog/BlogSide.vue')['default']
    Edit: typeof import('./components/Blog/Edit.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpMagicStick: typeof import('~icons/ep/magic-stick')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    Index: typeof import('./components/Home/Index.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    List: typeof import('./components/Blog/List.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    Read: typeof import('./components/Blog/Read.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Home/Search.vue')['default']
    Side: typeof import('./components/Side.vue')['default']
    WebCollect: typeof import('./components/Home/WebCollect.vue')['default']
  }
}

export {}
